### ISSUE TITLE
Join group link not working correctly on iPhone/mobile.

### ISSUE THREAD

**Issue by ChrisChasm** [ChasmSolutions/zume-project-plugin#13]
Issue: The situation is that when a person already has a Zume account and they are sent a link to join a group. On the iPhone, responding to this link take them to the registration page. If they then proceed to register again they either get a warning that the email address is already taken, or if they register with a different email address, they are not connected to the group.

**Comment by ChrisChasm** [comment]
One possible fix to this is to both offer a login option on the registration page that will guide a person who already has an account to login instead of register.

**Comment by ChrisChasm** [comment]
@coracca If you are not too busy monday morning can you look at this issue. I talked with Justin, who reported the problem and can give more details if you need them. But you built the link to group section, it would probably be faster for you to address it.

**Comment by corsacca** [comment]
@ChrisChasm Yeah, the link should point to a page that has the log in option too. 
I can't replicate the not being added to a group issue. I opened the link both on android and on an iphone, registered, confirmed the email, and found the group i was invited to. 
Zume saves the group id form the link, so no matter what email you use to register it should add you to the group.
Next Step: Add link to log in on the register page

**Comment by corsacca** [comment]
@ChrisChasm , in general if you have more information about which device and which browser it will help us debug issues more efficiently.

**Comment by ChrisChasm** [comment]
Corrected the link issue by sending people to the home page instead of the registration page. But I need to create a landing page for the link that offers people the chances to login, register, or explore the overview. Either way we will capture the session variables and associate them with the group when they login or register.
